# For more information about the configurations used in this file, please
# see the Travis CI documentation: https://docs.travis-ci.com

language: python
dist: xenial
python:
  - '3.6'

node_js:
  - "10"

services:
  - docker

cache:
  pip: true
  directories:
  - node_modules  # NPM packages

env:
  global:
  # These env var are used by createdb/dropdb/psql commands.
  - PGDATABASE=localhost
  - PGHOST=localhost
  - PGUSER=postgres
  - PGPORT=5432
  - DATABASE_URL=postgres://${PGUSER}@${PGHOST}:${PGPORT}/${PGDATABASE}
  - DOCKER_POSTGRES_IMAGE=mdillon/postgis:11

before_script:
  - sudo service postgresql stop
  - docker run --rm --name pg-docker -d -p ${PGPORT}:5432 --tmpfs /var/lib/postgresql/data:rw ${DOCKER_POSTGRES_IMAGE}
  {%- if cookiecutter.postgis.lower() == 'y' %}
  - psql -c "CREATE EXTENSION postgis;"  # @TODO: Fix this
  {%- endif %}

install:
  - pip install -r requirements/development.txt
  {%- if cookiecutter.webpack.lower() == 'y' %}
  - npm install
  {%- endif %}

script:
- flake8
{% if cookiecutter.webpack.lower() == 'y' %}- npm run build{% endif %}
- py.test --cov -v --tb=native
{% if cookiecutter.add_ansible.lower() == 'y' %}- ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check{% endif %}

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]

{%- if cookiecutter.enable_heroku_deployment.lower() == 'y' %}
deploy:
  provider: heroku
  buildpack: python
  strategy: api
  api_key:
    # travis encrypt $(heroku auth:token) --add deploy.api_key
    secure: <add_heroku_auth_token_here>
  app:
    master: {{ cookiecutter.main_module }}-dev
    qa: {{ cookiecutter.main_module }}-qa
    prod: {{ cookiecutter.main_module }}-prod
  on:
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.github_repository }}
{% endif %}
